In [1]:
import numpy as np
#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

In [7]:
X.shape,y

((3, 4), array([[1],
        [1],
        [0]]))

In [3]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [4]:
def derivatives_sigmoid(x):
    return x * (1 - x)

In [5]:
#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [8]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [9]:
wh,bh,wout,bout

(array([[ 0.1944098 ,  0.92355117,  0.66888584],
        [ 0.78740691,  0.20032913,  0.21891826],
        [ 0.11676001,  0.29258732,  0.83081415],
        [ 0.04684893,  0.26076718,  0.18045975]]),
 array([[ 0.02062037,  0.73666793,  0.82509994]]),
 array([[ 0.99582685],
        [ 0.37357321],
        [ 0.43680794]]),
 array([[ 0.73358247]]))

In [14]:
def Backprapogation(output,hiddenlayer_activations):
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr


def nuralnet_e():
    for i in range(epoch):

        #Forward Propogation
        hidden_layer_input1=np.dot(X,wh)
        hidden_layer_input=hidden_layer_input1 + bh
        hiddenlayer_activations = sigmoid(hidden_layer_input)
        output_layer_input1=np.dot(hiddenlayer_activations,wout)
        output_layer_input= output_layer_input1+ bout
        output = sigmoid(output_layer_input)
#         print output
    return output
print nuralnet_e()

[[ 0.88477006]
 [ 0.88747905]
 [ 0.88663117]]
