In [1]:
import numpy as np

In [2]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [3]:
#Step 2 build model

num_epochs = 100

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,4)) - 1
syn2 = 2*np.random.random((4,1)) - 1
print "random weights"
print syn0,syn1,syn2

random weights
[[ 0.84350268 -0.22236604  0.04724977 -0.0316298 ]
 [ 0.48609715 -0.22162039  0.65487515 -0.17228443]
 [ 0.39431567  0.25777402  0.80779165  0.64330415]] [[-0.79576949 -0.9709655   0.05784039 -0.48162612]
 [-0.39892797  0.59764663 -0.58268014 -0.74006354]
 [ 0.4134771  -0.22070293 -0.32593475 -0.49160432]
 [-0.70142994 -0.73302049  0.29863656  0.64051761]] [[-0.75387543]
 [ 0.57203812]
 [ 0.86371382]
 [ 0.57877475]]


In [4]:
def sigmoide_and_its_derivative(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [11]:
for m in xrange(num_epochs):
    k0 = x
    k1 = sigmoide_and_its_derivative(np.dot(k0, syn0))
    k2 = sigmoide_and_its_derivative(np.dot(k1, syn1))
    k3 = sigmoide_and_its_derivative(np.dot(k2, syn2))
    
    print "y--------------k3"
    print k3
    output_error = y-k3
    delta3 = output_error*(sigmoide_and_its_derivative(k3,deriv=True))
    output_error2 = delta3.dot(syn2.T)
    delta2 = output_error2= delta3*(sigmoide_and_its_derivative(k2,deriv=True))
    output_error1 = delta2.dot(syn1.T)
    #print "k1_error"
    #print k1    
    delta1 = output_error1 *(sigmoide_and_its_derivative(k1,deriv=True))
    syn2 =syn2+ k1.T.dot(delta3)
    syn1 =syn1+ k1.T.dot(delta2)
    syn0 =syn0+ k0.T.dot(delta1)
    

y--------------k3
[[ 0.62493371]
 [ 0.61719119]
 [ 0.62366785]
 [ 0.61669885]]
