In [1]:
import numpy as np

In [2]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [3]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,4)) - 1
syn2 = 2*np.random.random((4,1)) - 1
print "random weights"
print syn0,syn1,syn2

random weights
[[-0.81042316 -0.47477284  0.39209894  0.07381084]
 [-0.13740985  0.90466406 -0.86425758  0.74624023]
 [-0.92583022  0.70332531 -0.64254583 -0.12201188]] [[-0.74398006  0.70207833  0.60951754 -0.88663788]
 [-0.9175417   0.58939509  0.97052579 -0.27072001]
 [ 0.38486648 -0.09985252  0.14652786  0.40068452]
 [ 0.2961405  -0.30146541 -0.84568026  0.36691002]] [[ 0.21019834]
 [-0.7556301 ]
 [-0.25670869]
 [ 0.71006477]]


In [4]:
def sigmoide_and_its_derivative(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
for m in xrange(num_epochs):
    k0 = x
    k1 = sigmoide_and_its_derivative(np.dot(k0, syn0))
    k2 = sigmoide_and_its_derivative(np.dot(k1, syn1))
    k3 = sigmoide_and_its_derivative(np.dot(k2, syn2))
    
    #print "y--------------k3"
    #print k3
    output_error = y-k3
    if (m% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(output_error)))
    delta3 = output_error*(sigmoide_and_its_derivative(k3,deriv=True))
    output_error2 = delta3.dot(syn2.T)
    delta2 = output_error2= delta3*(sigmoide_and_its_derivative(k2,deriv=True))
    output_error1 = delta2.dot(syn1.T)
    #print "k1_error"
    #print k1    
    delta1 = output_error1 *(sigmoide_and_its_derivative(k1,deriv=True))
    syn2 =syn2+ k3.T.dot(delta3)
    syn1 =syn1+ k2.T.dot(delta2)
    syn0 =syn0+ k1.T.dot(delta1)
#     print k1.T.dot(delta)
#     print k1.T.dot(delta3)
#     print k1.T.dot(delta3)

        #print "output:" +str(k2)
        #print "actual out:"+str(y)
    

Error:0.253226663091


ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 