In [78]:
import numpy as np

In [79]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [80]:
from sklearn.datasets import load_iris
data= load_iris()
X=data.data
y= data.target
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [108]:
# output_list =[]
# for s in y_train:
#     if s==0:
#         output_list.append([0,0,1])
#     if s==1:
#         output_list.append([0,1,0])
#     if s==2:
#         output_list.append([1,0,0])
# y = np.array(output_list)
# print X_train
# x=X_train
# print y
x=X_train[10,:]
y=np.where(y_train == 2, 1,0 )
# new_y=list()
for s in y:
    new_y.append([s])


TypeError: list indices must be integers, not tuple

In [115]:
#Step 2 build model
y =np.array(new_y)
y= y[:10,:]
print y
num_epochs = 10

#initialize weights
syn0 = 2*np.random.random((4,4)) - 1
syn1 = 2*np.random.random((4,4)) - 1
syn2 = 2*np.random.random((4,1)) - 1
print "random weights"
print syn0,syn1,syn2
print x

[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
random weights
[[-0.02801788  0.55984202  0.77122498  0.30467337]
 [ 0.72380544  0.42021526  0.79433855 -0.24377234]
 [ 0.79351301  0.52595351  0.29989009 -0.11237807]
 [ 0.75639374 -0.76976532  0.14173921 -0.72400968]] [[-0.34989239  0.11586368  0.72993641  0.33957476]
 [-0.30912085  0.27362331  0.5743198  -0.63742834]
 [-0.09060007 -0.11958508  0.77007124 -0.49794748]
 [-0.11979598  0.49190993  0.89943133  0.67909657]] [[ 0.99077554]
 [-0.86619421]
 [-0.15511396]
 [ 0.2371973 ]]
[ 6.3  2.7  4.9  1.8]


In [116]:
def sigmoide_and_its_derivative(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [117]:
for m in xrange(num_epochs):
    k0 = x
    k1 = sigmoide_and_its_derivative(np.dot(k0, syn0))
    k2 = sigmoide_and_its_derivative(np.dot(k1, syn1))
    k3 = sigmoide_and_its_derivative(np.dot(k2, syn2))
    print k3

    #print "y--------------k3"
    print y
    output_error = y - k3    
    if (m % 10000) == 0:
#         print "1"
        print "Error:" + str(np.mean(np.abs(output_error)))
    delta3 = output_error*(sigmoide_and_its_derivative(k3,deriv=True))
    output_error2 = delta3.dot(syn2.T)
    delta2 = output_error2= delta3*(sigmoide_and_its_derivative(k2,deriv=True))
    output_error1 = delta2.dot(syn1.T)
    #print "k1_error"
    #print k1    
    delta1 = output_error1 *(sigmoide_and_its_derivative(k1,deriv=True))
    syn2 =syn2+ k2.T.dot(delta3)
    syn1 =syn1+ k1.T.dot(delta2)
    syn0 =syn0+k0.T.dot(delta1)
#     print k1.T.dot(delta)
#     print k1.T.dot(delta3)
#     print k1.T.dot(delta3)

        #print "output:" +str(k2)
        #print "actual out:"+str(y)
    

[ 0.43189178]
[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
Error:0.459135067997


ValueError: shapes (4,) and (10,1) not aligned: 4 (dim 0) != 10 (dim 0)

In [93]:
m="a"